name: Deploy to AWS
on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - 'cloudresume.html'
      - 'cloudresume.js'
      - 'cloudresume.css'
      - 'function.zip'
      - '.github/workflows/deploy.yml'
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0
    - name: Terraform Init
      run: terraform init -reconfigure
    - name: Terraform Plan
      id: plan
      run: terraform plan -detailed-exitcode
    - name: Terraform Apply
      if: steps.plan.outputs.exitcode == 2
      run: terraform apply -auto-approve
    - name: Upload static files to S3
      run: |
        aws s3 cp cloudresume.html s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.html
        aws s3 cp cloudresume.js s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.js
        aws s3 cp cloudresume.css s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.css
    - name: Create CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id E3V232V07RULP0 --paths "/*"