name: Deploy to AWS
on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - 'cloudresume.html'
      - 'cloudresume.js'
      - 'cloudresume.css'
      - '.github/workflows/deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Debug Secrets
      run: |
        echo "TEST_AWS_ACCESS_KEY_ID is set: ${TEST_AWS_ACCESS_KEY_ID:+set}"
        echo "TEST_AWS_SECRET_ACCESS_KEY is set: ${TEST_AWS_SECRET_ACCESS_KEY:+set}"
        echo "TEST_AWS_SESSION_TOKEN is set: ${TEST_AWS_SESSION_TOKEN:+set}"
      env:
        TEST_AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        TEST_AWS_SESSION_TOKEN: ${{ secrets.TEST_AWS_SESSION_TOKEN }}
    - name: Configure AWS Credentials for Prod Account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Configure AWS Credentials for Test Account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.TEST_AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0
    - name: Terraform Init
      run: terraform init -reconfigure
    - name: Terraform Apply
      run: terraform apply -auto-approve
    - name: Upload static files to S3
      run: |
        aws s3 cp cloudresume.html s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.html
        aws s3 cp cloudresume.js s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.js
        aws s3 cp cloudresume.css s3://trison-cloud-resume-prod-mjcsikwf/cloudresume.css
    - name: Create CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id E3V232V07RULP0 --paths "/*"